<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Opertions on column

In [ ]:
import pandas as pd
d={
    "name":["rahul","anushka","sini"],
    "salary":[100,200,300]
}
df=pd.DataFrame(data=d)
#add columns
df["holidays"]=df["salary"]/100
df["decrement"]=[10,20,30]
#delete columns
df.drop(["salary","name"],axis=1,inplace=True)

OPERATIONS ON ROW

In [ ]:
import pandas as pd
d={
    "name":["rahul","anushka","sini"],
    "salary":[100,200,300]
}
df=pd.DataFrame(data=d)
print(df.loc[2,"name"])
print(df.iloc[2,0])

sini
sini

In [ ]:
#get single row using loc
import pandas as pd
d={
    "name":["rahul","anushka","sini"],
    "salary":[100,200,300]
}
df=pd.DataFrame(data=d)
#get single row using iloc
print(df.iloc[0])
#get single row using loc
print(df.loc[0])
#get multi row using loc
print(df.loc[0:1])
#get multi row using iloc
print(df.iloc[[0,1]])
#sub data get using loc
df1=df.iloc[0:2,[0]]
df1
#sub data get using loc
df2=df.loc[0:2,["name"]]
df2

name      rahul
salary      100
Name: 0, dtype: object
name      rahul
salary      100
Name: 0, dtype: object
      name  salary
0    rahul     100
1  anushka     200
      name  salary
0    rahul     100
1  anushka     200

      name
0    rahul
1  anushka
2     sini

In [ ]:
#PRACTICE QUESTION
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)
#add column
df["incentives"]=df["Salary"]*0.1
#delete column
df.drop(["Salary"],axis=1,inplace=True)
#get single row using iloc
print(df.iloc[0])
#get single row using loc
print(df.loc[0])
#get multi row using loc
print(df.loc[0:1])
#get multi row using iloc
print(df.iloc[[0,1]])

Emp_ID           101
Name            Amit
Department        IT
Experience         2
incentives    5000.0
Name: 0, dtype: object
Emp_ID           101
Name            Amit
Department        IT
Experience         2
incentives    5000.0
Name: 0, dtype: object
   Emp_ID  Name Department  Experience  incentives
0     101  Amit         IT           2      5000.0
1     102  Riya         HR           3      4500.0
   Emp_ID  Name Department  Experience  incentives
0     101  Amit         IT           2      5000.0
1     102  Riya         HR           3      4500.0

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/studentdata.json"
df= pd.read_json(url)
#add columns
df["hindi"]=df["maths"]+30
#remove column
df.drop(["maths"],axis=1,inplace=True)
#get single row using iloc
print(df.iloc[0])
#get single row using loc
print(df.loc[0])
#get multi row using loc
print(df.loc[0:1])
#get multi row using iloc
print(df.iloc[[0,1]])
#2 specific value by using jump
print(df.iloc[[0,1],[0,1,2]])
#
df

name       arun
gender     Male
physics      88
english      78
hindi       117
Name: 0, dtype: object
name       arun
gender     Male
physics      88
english      78
hindi       117
Name: 0, dtype: object
     name gender  physics  english  hindi
0    arun   Male       88       78    117
1  rajesh   Male       96       95    130
     name gender  physics  english  hindi
0    arun   Male       88       78    117
1  rajesh   Male       96       95    130

IndexError: positional indexers are out-of-bounds

In [ ]:
# filtering data
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/studentdata.json"
df= pd.read_json(url)
#filter1
#df[df["english"]==95]

#filter2
#df[df["maths"]<60]

#filter3
#df[df["physics"]<= 56]

#filter4
df[df["maths" and "english"]>=100]

     name  gender  physics  maths  english
10  Gowri  Female      100    100      100